/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_database;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class daftar_user extends javax.swing.JFrame {

    /**
     * Creates new form daftar_user
     */
    private String[] JK = {"Pilih...", "Laki-laki", "Wanita"};

    private String massage;
    crud_user aa = new crud_user();

    public daftar_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jenisKelamin = new javax.swing.JComboBox<>();
        daftar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        agama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noHP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(485, 570));
        setSize(new java.awt.Dimension(510, 580));
        getContentPane().setLayout(null);
        getContentPane().add(nama);
        nama.setBounds(190, 170, 264, 31);
        getContentPane().add(email);
        email.setBounds(190, 210, 264, 30);
        getContentPane().add(password);
        password.setBounds(190, 250, 264, 30);
        getContentPane().add(alamat);
        alamat.setBounds(190, 290, 264, 30);

        jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(JK));
        getContentPane().add(jenisKelamin);
        jenisKelamin.setBounds(190, 330, 264, 32);

        daftar.setBackground(new java.awt.Color(255, 255, 255));
        daftar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        daftar.setForeground(new java.awt.Color(255, 182, 0));
        daftar.setText("Daftar");
        daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarActionPerformed(evt);
            }
        });
        getContentPane().add(daftar);
        daftar.setBounds(190, 500, 101, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Lengkap");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 180, 110, 19);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 220, 37, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 260, 68, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 300, 46, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 340, 98, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIK");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 380, 24, 19);
        getContentPane().add(nik);
        nik.setBounds(190, 370, 264, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Agama");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 420, 46, 19);
        getContentPane().add(agama);
        agama.setBounds(190, 410, 264, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nomor HP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 460, 69, 19);
        getContentPane().add(noHP);
        noHP.setBounds(190, 450, 264, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Daftar.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -10, 500, 130);

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DAFTAR USER");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 125, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarActionPerformed
        if (nama.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data is not Full!");
            nama.requestFocus();
        } else if (email.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data is not Full!");
            email.requestFocus();
        } else if (password.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data is not Full!");
            password.requestFocus();
        } else if (alamat.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data is not Full!");
            alamat.requestFocus();
        } else {
            try {
                aa.setJenisKelamin(jenisKelamin.getSelectedItem().toString());
                aa.setNama(nama.getText());
                aa.setEmail(email.getText());
                aa.setPassword(password.getText());
                aa.setAlamat(alamat.getText());
                aa.setNik(nik.getText());
                aa.setAgama(agama.getText());
                aa.setNoHP(noHP.getText());
                aa.daftar(aa.getNama(), aa.getEmail(), aa.getPassword(), aa.getJenisKelamin(), aa.getNik(), aa.getAlamat(), aa.getAgama(), aa.getnoHP());
                JOptionPane.showMessageDialog(null, "Registrasi Selesai, Silahkan Login", "Information",
                        JOptionPane.INFORMATION_MESSAGE);
                Login.preview();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Masih Kosong", "Information",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_daftarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void preview() {
        daftar_user form = new daftar_user();
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.getContentPane().setBackground(Color.decode("#ffb600"));
        form.setVisible(true);
    }
    
    public static void main(String args[]) {
        preview();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agama;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton daftar;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jenisKelamin;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField noHP;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
