/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_database;

import java.awt.Color;

/**
 *
 * @author Lenovo
 */
public class Daftar_Kamar extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_Kamar
     */
    crud_hotel ob = new crud_hotel();
    public Daftar_Kamar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stokStandartRoom = new javax.swing.JTextField();
        stokSuperriorRoom = new javax.swing.JTextField();
        stokDeluxeRoom = new javax.swing.JTextField();
        stokStudioRoom = new javax.swing.JTextField();
        stokSuiteRoom = new javax.swing.JTextField();
        stokPresidentialRoom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 510));
        getContentPane().setLayout(null);
        getContentPane().add(stokStandartRoom);
        stokStandartRoom.setBounds(210, 180, 260, 31);
        getContentPane().add(stokSuperriorRoom);
        stokSuperriorRoom.setBounds(210, 220, 260, 31);
        getContentPane().add(stokDeluxeRoom);
        stokDeluxeRoom.setBounds(210, 260, 260, 31);
        getContentPane().add(stokStudioRoom);
        stokStudioRoom.setBounds(210, 300, 260, 31);
        getContentPane().add(stokSuiteRoom);
        stokSuiteRoom.setBounds(210, 340, 260, 31);
        getContentPane().add(stokPresidentialRoom);
        stokPresidentialRoom.setBounds(210, 380, 260, 31);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stok Standart Room");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 190, 140, 16);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stok Superrior Room");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 230, 150, 16);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stok Deluxe Room");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 270, 130, 16);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stok Studio Room");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 310, 130, 16);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stok Suite Room");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 350, 120, 16);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stok Presidential Room");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 390, 160, 16);

        simpan.setBackground(new java.awt.Color(255, 255, 255));
        simpan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 182, 0));
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(30, 425, 440, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Daftar.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 500, 120);

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SET STOK KAMAR");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 130, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
            ob.setStokStandartRoom(stokStandartRoom.getText());
            ob.setStokSuperriorRoom(stokSuperriorRoom.getText());
            ob.setStokDeluxeRoom(stokDeluxeRoom.getText());
            ob.setStokStudioRoom(stokStudioRoom.getText());
            ob.setStokSuiteRoom(stokSuiteRoom.getText());
            ob.setStokPresidetialRoom(stokPresidentialRoom.getText());
            ob.daftarStokKamar(ob.getStokStandartRoom(), ob.getStokSuperriorRoom(), ob.getStokDeluxeRoom(), ob.getStokStudioRoom(), ob.getStokSuiteRoom(), ob.getStokPresidentialRoom());
            dispose();
            Daftar_Harga.preview();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_simpanActionPerformed

    public static void preview() {
        Daftar_Kamar form = new Daftar_Kamar();
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.getContentPane().setBackground(Color.decode("#ffb600"));
        form.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        preview();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stokDeluxeRoom;
    private javax.swing.JTextField stokPresidentialRoom;
    private javax.swing.JTextField stokStandartRoom;
    private javax.swing.JTextField stokStudioRoom;
    private javax.swing.JTextField stokSuiteRoom;
    private javax.swing.JTextField stokSuperriorRoom;
    // End of variables declaration//GEN-END:variables
}
