/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_database;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Daftar_Harga extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_Harga
     */
    crud_hotel ob = new crud_hotel();
    public Daftar_Harga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hargaPresidentialRoom = new javax.swing.JTextField();
        hargaSuiteRoom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hargaStandartRoom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hargaSuperriorRoom = new javax.swing.JTextField();
        hargaStudioRoom = new javax.swing.JTextField();
        hargaDeluxeRoom = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 510));
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Harga Permalam Deluxe Room");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 270, 220, 16);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Harga Permalam Studio Room");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 310, 220, 16);
        getContentPane().add(hargaPresidentialRoom);
        hargaPresidentialRoom.setBounds(280, 380, 190, 31);
        getContentPane().add(hargaSuiteRoom);
        hargaSuiteRoom.setBounds(280, 340, 190, 31);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Harga Permalam Suite Room");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 350, 220, 16);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Harga Permalam Presidential Room");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 390, 220, 16);
        getContentPane().add(hargaStandartRoom);
        hargaStandartRoom.setBounds(280, 180, 190, 31);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Harga Permalam Standart Room");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 220, 16);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga Permalam Superrior Room");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 230, 220, 16);
        getContentPane().add(hargaSuperriorRoom);
        hargaSuperriorRoom.setBounds(280, 220, 190, 31);
        getContentPane().add(hargaStudioRoom);
        hargaStudioRoom.setBounds(280, 300, 190, 31);
        getContentPane().add(hargaDeluxeRoom);
        hargaDeluxeRoom.setBounds(280, 260, 190, 31);

        simpan.setBackground(new java.awt.Color(255, 255, 255));
        simpan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 182, 0));
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(30, 420, 440, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Daftar.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 120);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SET HARGA KAMAR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 130, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
            ob.setHargaStandartRoom(hargaStandartRoom.getText());
            ob.setHargaSuperriorRoom(hargaSuperriorRoom.getText());
            ob.setHargaDeluxeRoom(hargaDeluxeRoom.getText());
            ob.setHargaStudioRoom(hargaStudioRoom.getText());
            ob.setHargaSuiteRoom(hargaSuiteRoom.getText());
            ob.setHargaPresidetialRoom(hargaPresidentialRoom.getText());
            ob.daftarHargaKamar(ob.getHargaStandartRoom(), ob.getHargaSuperriorRoom(), ob.getHargaDeluxeRoom(), ob.getHargaStudioRoom(), ob.getHargaSuiteRoom(), ob.getHargaPresidentialRoom());
            JOptionPane.showMessageDialog(null, "Registrasi Selesai Silahkan Login");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_simpanActionPerformed

    public static void preview() {
        Daftar_Harga form = new Daftar_Harga();
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.getContentPane().setBackground(Color.decode("#ffb600"));
        form.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        preview();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaDeluxeRoom;
    private javax.swing.JTextField hargaPresidentialRoom;
    private javax.swing.JTextField hargaStandartRoom;
    private javax.swing.JTextField hargaStudioRoom;
    private javax.swing.JTextField hargaSuiteRoom;
    private javax.swing.JTextField hargaSuperriorRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
