/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_database;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Daftar_Hotel extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_Hotel
     */
    crud_hotel ob = new crud_hotel();

    public Daftar_Hotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaHotel = new javax.swing.JTextField();
        alamatHotel = new javax.swing.JTextField();
        nomorTelp = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        pengelola = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel11.setText("Harga Permalam");

        jLabel12.setText("Harga Permalam");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Daftar.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SET HARGA KAMAR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 510));
        setPreferredSize(new java.awt.Dimension(510, 510));
        getContentPane().setLayout(null);
        getContentPane().add(namaHotel);
        namaHotel.setBounds(180, 180, 290, 31);
        getContentPane().add(alamatHotel);
        alamatHotel.setBounds(180, 220, 290, 31);
        getContentPane().add(nomorTelp);
        nomorTelp.setBounds(180, 260, 290, 31);
        getContentPane().add(email);
        email.setBounds(180, 300, 290, 31);
        getContentPane().add(password);
        password.setBounds(180, 340, 290, 31);
        getContentPane().add(pengelola);
        pengelola.setBounds(180, 380, 290, 31);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nama Hotel");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 190, 110, 16);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Alamat Hotel");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 230, 110, 16);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nomor Telpon");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 270, 120, 16);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Email Hotel");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 310, 100, 16);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Password");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 350, 100, 16);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nama Pengelola");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 390, 130, 16);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 182, 0));
        jButton1.setText("Daftar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 420, 440, 33);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Daftar.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 120);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SET DETAIL HOTEL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 130, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ob.setNamaHotel(namaHotel.getText());
            ob.setAlamatHotel(alamatHotel.getText());
            ob.setNoTelpHotel(nomorTelp.getText());
            ob.setEmailHotel(email.getText());
            ob.setPasswordHotel(password.getText());
            ob.setPengelolaHotel(pengelola.getText());
            ob.daftarHotel(ob.getNamaHotel(), ob.getAlamatHotel(), ob.getNoTelpHotel(), ob.getEmailHotel(), ob.getPasswordHotel(), ob.getPengelola());
        } catch (Exception e) {
            System.out.println(e);
        }
        try {
            ob.tersedia("Tersedia", "Tersedia", "Tersedia", "Tersedia", "Tersedia", "Tersedia");
        } catch (Exception e) {
            System.out.println(e);
        }
        dispose();
        Daftar_Kamar.preview();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void preview() {
        Daftar_Hotel form = new Daftar_Hotel();
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.getContentPane().setBackground(Color.decode("#ffb600"));
        form.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        preview();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatHotel;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField namaHotel;
    private javax.swing.JTextField nomorTelp;
    private javax.swing.JTextField password;
    private javax.swing.JTextField pengelola;
    // End of variables declaration//GEN-END:variables
}
