/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_database;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private String massage;
    crud_user aa = new crud_user();

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 182, 0));
        setMinimumSize(new java.awt.Dimension(405, 330));
        getContentPane().setLayout(null);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        login.setForeground(new java.awt.Color(255, 182, 0));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(160, 250, 90, 30);
        getContentPane().add(email);
        email.setBounds(100, 160, 278, 29);

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(100, 200, 278, 27);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 210, 60, 15);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 50, 15);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Login.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 100);

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN USER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 110, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if (email.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
            email.requestFocus();
        } else if (password.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
            password.requestFocus();
        } else {
            aa.setEmail(email.getText());
            aa.setPassword(password.getText());
            Session.setEmail(email.getText());
            massage = aa.loginCheck(aa.getEmail(), aa.getPassword());
            if (Session.getLoginStatus() == "Active") {
                dispose();
                Pesan.preview();
            } else {
                JOptionPane.showMessageDialog(null, "Sorry, Can't Login");
            }
        }        
    }//GEN-LAST:event_loginActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (email.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi Data Secara Lengkap");
                email.requestFocus();
            } else if (password.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi Data Secara Lengkap");
                password.requestFocus();
            } else {
                aa.setEmail(email.getText());
                aa.setPassword(password.getText());
                Session.setEmail(email.getText());
                massage = aa.loginCheck(aa.getEmail(), aa.getPassword());
                if (Session.getLoginStatus() == "Active") {
                    dispose();
                    Pesan.preview();
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry, Can't Login");
                }
            }
        }
    }//GEN-LAST:event_passwordKeyPressed

    public static void preview() {
        Login form = new Login();
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.getContentPane().setBackground(Color.decode("#ffb600"));
        form.setVisible(true);
    }

    public static void main(String args[]) {
        try {
            preview();            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
