/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_database;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Login_Hotel extends javax.swing.JFrame {

    /**
     * Creates new form Login_Hotel
     */
    private String massage;
    crud_hotel aa = new crud_hotel();

    public Login_Hotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Login.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 182, 0));
        setMinimumSize(new java.awt.Dimension(405, 330));
        getContentPane().setLayout(null);
        getContentPane().add(email);
        email.setBounds(120, 160, 250, 30);
        getContentPane().add(password);
        password.setBounds(120, 200, 250, 30);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 182, 0));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(160, 250, 80, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Login.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 100);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 210, 60, 15);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email Hotel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 70, 15);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGIN HOTEL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 110, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if (email.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
            email.requestFocus();
        } else if (password.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Sorry, Data Not Complete");
            password.requestFocus();
        } else {
            aa.setEmailHotel(email.getText());
            aa.setPasswordHotel(password.getText());
            Session_Hotel.setEmailHotel(email.getText());
            massage = aa.loginCheck(aa.getEmailHotel(), aa.getPasswordHotel());
            if (Session_Hotel.getLoginStatus() == "Active") {
                dispose();
                Menu_Hotel.preview();
            } else {
                JOptionPane.showMessageDialog(null, "Sorry, Can't Login");
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    public static void preview() {
        Login_Hotel form = new Login_Hotel();
        form.setResizable(false);
        form.setLocationRelativeTo(null);
        form.getContentPane().setBackground(Color.decode("#ffb600"));
        form.setVisible(true);
    }
    
    /**AA
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        preview();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton login;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
