/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_database;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static uas_database.Login.preview;

/**
 *
 * @author Lenovo
 */
public class Menu_Hotel extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Hotel
     */
    crud_hotel ob = new crud_hotel();

    public Menu_Hotel() {
        if (Session_Hotel.getLoginStatus() == "Active") {
            initComponents();
            daftar_hotel();
            tampilData();
        } else {
            dispose();
            Login_Hotel.preview();
        }
    }

    public void daftar_hotel() {
        hello.setText("Hello " + Session_Hotel.getNamaHotel());
        email.setText(Session_Hotel.getEmailHotel());
        namaHotel.setText(Session_Hotel.getNamaHotel());
        alamatHotel.setText(Session_Hotel.getAlamatHotel());
        nomorTelp.setText(Session_Hotel.getNoTelpHotel());
        password.setText(Session_Hotel.getPasswordHotel());
        pengelola.setText(Session_Hotel.getPengelola());

        email.setEditable(false);
        namaHotel.setEditable(false);
        alamatHotel.setEditable(false);
        nomorTelp.setEditable(false);
        password.setEditable(false);
        pengelola.setEditable(false);

        stokDeluxeRoom.setEditable(false);
        stokPresidentialRoom.setEditable(false);
        stokStandartRoom.setEditable(false);
        stokStudioRoom.setEditable(false);
        stokSuiteRoom.setEditable(false);
        stokSuperriorRoom.setEditable(false);

        hargaStandartRoom.setEditable(false);
        hargaSuperriorRoom.setEditable(false);
        hargaDeluxeRoom.setEditable(false);
        hargaStudioRoom.setEditable(false);
        hargaSuiteRoom.setEditable(false);
        hargaPresidentialRoom.setEditable(false);
    }

    public void tampilData() {
        try {
            mariadbConnection db = new mariadbConnection();
            Connection con = db.getConnection();
            Statement stt = con.createStatement();
            String CRUDqueryStok = "select * from stok_kamar where id_hotel = " + Session_Hotel.getIDHotel();
            String CRUDqueryHarga = "select * from harga_kamar_hotel where id_hotel = " + Session_Hotel.getIDHotel();
            ResultSet resHarga = stt.executeQuery(CRUDqueryHarga);
            ResultSet resStok = stt.executeQuery(CRUDqueryStok);

            while (resHarga.next()) {
                Object[] ob = new Object[6];
                ob[0] = resHarga.getString("harga_standart_room");
                ob[1] = resHarga.getString("harga_superrior_room");
                ob[2] = resHarga.getString("harga_deluxe_room");
                ob[3] = resHarga.getString("harga_studio_room");
                ob[4] = resHarga.getString("harga_suite_room");
                ob[5] = resHarga.getString("harga_presidential_room");
                hargaStandartRoom.setText((String) ob[0]);
                hargaSuperriorRoom.setText((String) ob[1]);
                hargaDeluxeRoom.setText((String) ob[2]);
                hargaStudioRoom.setText((String) ob[3]);
                hargaSuiteRoom.setText((String) ob[4]);
                hargaPresidentialRoom.setText((String) ob[5]);
            }

            while (resStok.next()) {
                Object[] ob = new Object[6];
                ob[0] = resStok.getString("stok_standart_room");
                ob[1] = resStok.getString("stok_superrior_room");
                ob[2] = resStok.getString("stok_deluxe_room");
                ob[3] = resStok.getString("stok_studio_room");
                ob[4] = resStok.getString("stok_suite_room");
                ob[5] = resStok.getString("stok_presidential_room");
                stokStandartRoom.setText((String) ob[0]);
                stokSuperriorRoom.setText((String) ob[1]);
                stokDeluxeRoom.setText((String) ob[2]);
                stokStudioRoom.setText((String) ob[3]);
                stokSuiteRoom.setText((String) ob[4]);
                stokPresidentialRoom.setText((String) ob[5]);
            }

            resHarga.close();
            resStok.close();
            stt.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hargaSuperriorRoom = new javax.swing.JTextField();
        hargaStudioRoom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hargaDeluxeRoom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        editHarga = new javax.swing.JButton();
        hargaPresidentialRoom = new javax.swing.JTextField();
        hargaSuiteRoom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hargaStandartRoom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        pengelola = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        namaHotel = new javax.swing.JTextField();
        alamatHotel = new javax.swing.JTextField();
        nomorTelp = new javax.swing.JTextField();
        stokStudioRoom = new javax.swing.JTextField();
        stokSuiteRoom = new javax.swing.JTextField();
        stokPresidentialRoom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stokStandartRoom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stokSuperriorRoom = new javax.swing.JTextField();
        editStok = new javax.swing.JButton();
        stokDeluxeRoom = new javax.swing.JTextField();
        hello = new javax.swing.JLabel();
        Konfirmasi = new javax.swing.JButton();
        konfirmasiStok = new javax.swing.JButton();
        konfirmasiHarga = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Harga Permalam");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Harga Permalam");

        editHarga.setBackground(new java.awt.Color(255, 255, 255));
        editHarga.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        editHarga.setForeground(new java.awt.Color(255, 182, 0));
        editHarga.setText("Ganti Harga Kamar Permalam");
        editHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHargaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Harga Permalam");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Harga Permalam");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Harga Permalam");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga Permalam");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nama Hotel");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Alamat Hotel");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nomor Telpon");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Email Hotel");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Password");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nama Pengelola");

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 182, 0));
        edit.setText("Ganti Profil Hotel");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stok Standart Room");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stok Superrior Room");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stok Deluxe Room");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stok Studio Room");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stok Suite Room");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stok Presidential Room");

        editStok.setBackground(new java.awt.Color(255, 255, 255));
        editStok.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        editStok.setForeground(new java.awt.Color(255, 182, 0));
        editStok.setText("Ganti Stok kamar");
        editStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStokActionPerformed(evt);
            }
        });

        hello.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        hello.setForeground(new java.awt.Color(255, 255, 255));
        hello.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hello.setText("Hello");

        Konfirmasi.setBackground(new java.awt.Color(255, 255, 255));
        Konfirmasi.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Konfirmasi.setForeground(new java.awt.Color(255, 182, 0));
        Konfirmasi.setText("Konfirmasi");
        Konfirmasi.setEnabled(false);
        Konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonfirmasiActionPerformed(evt);
            }
        });

        konfirmasiStok.setBackground(new java.awt.Color(255, 255, 255));
        konfirmasiStok.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        konfirmasiStok.setForeground(new java.awt.Color(255, 182, 0));
        konfirmasiStok.setText("Konfirmasi");
        konfirmasiStok.setEnabled(false);
        konfirmasiStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiStokActionPerformed(evt);
            }
        });

        konfirmasiHarga.setBackground(new java.awt.Color(255, 255, 255));
        konfirmasiHarga.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        konfirmasiHarga.setForeground(new java.awt.Color(255, 182, 0));
        konfirmasiHarga.setText("Konfirmasi");
        konfirmasiHarga.setEnabled(false);
        konfirmasiHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiHargaActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Logo_Daftar.jpg"))); // NOI18N
        jLabel11.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Menu Hotel");

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 182, 0));
        logout.setText("Keluar");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pengelola, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomorTelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamatHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Konfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stokSuperriorRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stokStandartRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(stokPresidentialRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stokSuiteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stokStudioRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(stokDeluxeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(editStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(konfirmasiStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(konfirmasiHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hargaStandartRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hargaSuperriorRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hargaDeluxeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hargaStudioRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hargaSuiteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(38, 38, 38)
                                .addComponent(hargaPresidentialRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(logout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hello)
                    .addComponent(jLabel12)
                    .addComponent(logout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alamatHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nomorTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pengelola, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(hargaStandartRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hargaSuperriorRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(hargaDeluxeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(hargaStudioRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hargaSuiteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hargaPresidentialRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(konfirmasiHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Konfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokStandartRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokSuperriorRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokDeluxeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokStudioRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokSuiteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokPresidentialRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editStok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(konfirmasiStok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHargaActionPerformed
        hargaStandartRoom.setEditable(true);
        hargaSuperriorRoom.setEditable(true);
        hargaDeluxeRoom.setEditable(true);
        hargaStudioRoom.setEditable(true);
        hargaSuiteRoom.setEditable(true);
        hargaPresidentialRoom.setEditable(true);
        konfirmasiHarga.setEnabled(true);
        editHarga.setEnabled(false);
    }//GEN-LAST:event_editHargaActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        email.setEditable(true);
        namaHotel.setEditable(true);
        alamatHotel.setEditable(true);
        nomorTelp.setEditable(true);
        password.setEditable(true);
        pengelola.setEditable(true);
        Konfirmasi.setEnabled(true);
        edit.setEnabled(false);
    }//GEN-LAST:event_editActionPerformed

    private void editStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStokActionPerformed
        stokDeluxeRoom.setEditable(true);
        stokPresidentialRoom.setEditable(true);
        stokStandartRoom.setEditable(true);
        stokStudioRoom.setEditable(true);
        stokSuiteRoom.setEditable(true);
        stokSuperriorRoom.setEditable(true);
        konfirmasiStok.setEnabled(true);
        editStok.setEnabled(false);
    }//GEN-LAST:event_editStokActionPerformed

    private void KonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonfirmasiActionPerformed
        ob.setNamaHotel(email.getText());
        ob.setAlamatHotel(namaHotel.getText());
        ob.setNoTelpHotel(nomorTelp.getText());
        ob.setEmailHotel(email.getText());
        ob.setPasswordHotel(password.getText());
        ob.setPengelolaHotel(pengelola.getText());
        ob.editHotel(ob.getNamaHotel(), ob.getAlamatHotel(), ob.getNoTelpHotel(), ob.getEmailHotel(), ob.getPasswordHotel(), ob.getPengelola());
        JOptionPane.showMessageDialog(null, "Data Telah Diedit");
        edit.setEnabled(true);
        Konfirmasi.setEnabled(false);
        email.setEditable(false);
        namaHotel.setEditable(false);
        alamatHotel.setEditable(false);
        nomorTelp.setEditable(false);
        password.setEditable(false);
        pengelola.setEditable(false);
    }//GEN-LAST:event_KonfirmasiActionPerformed

    private void konfirmasiStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiStokActionPerformed
        ob.setStokStandartRoom(stokStandartRoom.getText());
        ob.setStokSuperriorRoom(stokSuperriorRoom.getText());
        ob.setStokDeluxeRoom(stokDeluxeRoom.getText());
        ob.setStokStudioRoom(stokStudioRoom.getText());
        ob.setStokSuiteRoom(stokSuiteRoom.getText());
        ob.setStokPresidetialRoom(stokPresidentialRoom.getText());
        ob.editStokKamar(ob.getStokStandartRoom(), ob.getStokSuperriorRoom(), ob.getStokDeluxeRoom(), ob.getStokStudioRoom(), ob.getStokSuiteRoom(), ob.getStokPresidentialRoom());
        JOptionPane.showMessageDialog(null, "Data Stok Kamar Telah Diedit");
        editStok.setEnabled(true);
        konfirmasiStok.setEnabled(false);
        stokDeluxeRoom.setEditable(false);
        stokPresidentialRoom.setEditable(false);
        stokStandartRoom.setEditable(false);
        stokStudioRoom.setEditable(false);
        stokSuiteRoom.setEditable(false);
        stokSuperriorRoom.setEditable(false);
    }//GEN-LAST:event_konfirmasiStokActionPerformed

    private void konfirmasiHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiHargaActionPerformed
        ob.setHargaStandartRoom(hargaStandartRoom.getText());
        ob.setHargaSuperriorRoom(hargaSuperriorRoom.getText());
        ob.setHargaDeluxeRoom(hargaDeluxeRoom.getText());
        ob.setHargaStudioRoom(hargaStudioRoom.getText());
        ob.setHargaSuiteRoom(hargaSuiteRoom.getText());
        ob.setHargaPresidetialRoom(hargaPresidentialRoom.getText());
        ob.editHargaKamar(ob.getHargaStandartRoom(), ob.getHargaSuperriorRoom(), ob.getHargaDeluxeRoom(), ob.getHargaStudioRoom(), ob.getHargaSuiteRoom(), ob.getHargaPresidentialRoom());
        JOptionPane.showMessageDialog(null, "Data Harga Kamar Permalam Telah Diedit");
        editHarga.setEnabled(true);
        konfirmasiHarga.setEnabled(false);
        hargaStandartRoom.setEditable(false);
        hargaSuperriorRoom.setEditable(false);
        hargaDeluxeRoom.setEditable(false);
        hargaStudioRoom.setEditable(false);
        hargaSuiteRoom.setEditable(false);
        hargaPresidentialRoom.setEditable(false);
    }//GEN-LAST:event_konfirmasiHargaActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void preview() {
        Menu_Hotel form = new Menu_Hotel();
        form.setResizable(false);
        form.setLocationRelativeTo(null);
        form.getContentPane().setBackground(Color.decode("#ffb600"));
        form.setVisible(true);
    }

    public static void main(String args[]) {
        try {
            preview();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Konfirmasi;
    private javax.swing.JTextField alamatHotel;
    private javax.swing.JButton edit;
    private javax.swing.JButton editHarga;
    private javax.swing.JButton editStok;
    private javax.swing.JTextField email;
    private javax.swing.JTextField hargaDeluxeRoom;
    private javax.swing.JTextField hargaPresidentialRoom;
    private javax.swing.JTextField hargaStandartRoom;
    private javax.swing.JTextField hargaStudioRoom;
    private javax.swing.JTextField hargaSuiteRoom;
    private javax.swing.JTextField hargaSuperriorRoom;
    private javax.swing.JLabel hello;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton konfirmasiHarga;
    private javax.swing.JButton konfirmasiStok;
    private javax.swing.JButton logout;
    private javax.swing.JTextField namaHotel;
    private javax.swing.JTextField nomorTelp;
    private javax.swing.JTextField password;
    private javax.swing.JTextField pengelola;
    private javax.swing.JTextField stokDeluxeRoom;
    private javax.swing.JTextField stokPresidentialRoom;
    private javax.swing.JTextField stokStandartRoom;
    private javax.swing.JTextField stokStudioRoom;
    private javax.swing.JTextField stokSuiteRoom;
    private javax.swing.JTextField stokSuperriorRoom;
    // End of variables declaration//GEN-END:variables
}
